### PR TITLE
Preprod Support

### PR DESCRIPTION
**Pull request by trieloff**
same as adobe/helix-embed#306

### CODE REVIEW

**Comment by trieloff** [comment]
@tripodsan I think this fails due to the password change https://app.circleci.com/settings/project/github/adobe/helix-data-embed/environment-variables?return-to=https%3A%2F%2Fcircleci.com%2Fdashboard

**Comment by trieloff** [comment]
Did something change in OneDrive? I'm seeing this when testing locally:

```
acquire token with ROPC.
Error while refreshing access token Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE
    at Logger.createError (/code/helix-data-embed/node_modules/adal-node/lib/log.js:216:13)
    at WSTrustResponse.parse (/code/helix-data-embed/node_modules/adal-node/lib/wstrust-response.js:278:23)
    at WSTrustRequest._handleRSTR (/code/helix-data-embed/node_modules/adal-node/lib/wstrust-request.js:187:21)
    at /code/helix-data-embed/node_modules/adal-node/lib/wstrust-request.js:228:12
    at Request._callback (/code/helix-data-embed/node_modules/adal-node/lib/util.js:134:5)
    at Request.self.callback (/code/helix-data-embed/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/code/helix-data-embed/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/code/helix-data-embed/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
{ Error
    at Function.fromError (/code/helix-data-embed/node_modules/@adobe/helix-onedrive-support/src/StatusCodeError.js:24:17)
    at OneDrive.resolveShareLink (/code/helix-data-embed/node_modules/@adobe/helix-onedrive-support/src/OneDrive.js:274:37)
    at process._tickCallback (internal/process/next_tick.js:68:7) statusCode: 500 }

result { statusCode: 500,
  headers:
   { 'Content-Type': 'application/json',
     'cache-control': 'no-store, private, must-revalidate' } }
```

**Comment by tripodsan** [comment]
> Did something change in OneDrive? I'm seeing this when testing locally:

we changed the helix user password....

**Pull request merged**
