### PR TITLE
feat(data): multi sheet response

### PR DESCRIPTION
**Pull request by tripodsan**
see #315 

as discussed with @davidnuescheler 

BREAKING CHANGE:

- if no sheet is specified and the workbook has `helix-*` sheets, return all of the `helix-*` sheets
- unless it has a `helix-default` then only this one is returned
- if a workbook has no `helix-*` sheets, just return the first sheet (as before)
- sheet(s) can be selected with one or several `sheet=` query parameter

---

this PR also includes a change that respects the runtime for calculating the max response size:
https://github.com/adobe/helix-data-embed/pull/356/commits/12144b0f7dc66f36a3fad5119d3fa97e66cd0328

### CODE REVIEW

**Review by trieloff — COMMENTED** [review]
I think it would be great to have a schema for the response types. Right now, I see a number of differences between your implementation and mine in https://github.com/adobe/helix-pages/blob/prototype-three/test/pages3/pages3.test.js

Do we need the sheet parameter to be an array? Isn't a single sheet enough?

**Comment by tripodsan** [comment]
> Do we need the sheet parameter to be an array? Isn't a single sheet enough?

yes... `?sheet=one&sheet=two`

**Comment by tripodsan** [comment]
> https://github.com/adobe/helix-pages/blob/prototype-three/test/pages3/pages3.test.js

well, I think we shouldn't repeat past mistakes:
https://github.com/adobe/helix-pages/blob/3af4fb95edd53b5e647f3ce553503105504a116b/test/pages3/pages3.test.js#L77

see  the _spec_ here: https://github.com/adobe/helix-data-embed/issues/315#issuecomment-808609044

**Comment by tripodsan** [comment]
> differences between your implementation and mine

where did you implement your new  data-embed ?

**Comment by trieloff** [comment]
Here is my implementation: https://github.com/adobe/helix-pages/blob/prototype-three/assembly/handlers/json-handler.ts

**Comment by trieloff** [comment]
I can add a schema for #315 in `helix-shared`.

How would we persist a spreadsheet in S3? Would it use the same schema? Would it only include the `helix-*` sheets? Do we strip the `helix-*` prefix when returning sheets?

**Comment by tripodsan** [comment]
> I can add a schema for #315 in `helix-shared`.

rather here in data-embed.

**Comment by trieloff** [comment]
> rather here in `data-embed`.

Ok. I had hoped to be able to re-use the schema in my integration tests.

**Comment by tripodsan** [comment]
> Ok. I had hoped to be able to re-use the schema in my integration tests.

ok. then let's add it to helix-shared

**Comment by trieloff** [comment]
Sorry, saw it too late.

**Comment by tripodsan** [comment]
@trieloff I'll add some validation tests, once adobe/helix-shared#507 is released.

**Pull request merged**
